apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tsm-manuell
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 120Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
    sidecar:
      enabled: true
      autoLogin: true
  ingresses:
    - 'https://tsm-manuell.intern.dev.nav.no'
