apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tsm-manuell
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 40m
      memory: 300Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          # 0000-GA-SYFO-SENSITIV geografisk tilgang til sykmeldinger
          - id: "100e88eb-79af-4136-8bfe-f79b32021f43"
    sidecar:
      enabled: true
      autoLogin: true
  ingresses:
    - 'https://tsm-manuell.intern.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: modiacontextholder
          namespace: personoversikt
        - application: tsm-manuell-api
  env:
    - name: MODIA_CONTEXT_SCOPE
      value: api://prod-gcp.personoversikt.modiacontextholder/.default
    - name: MODIA_CONTEXT_URL
      value: http://modiacontextholder.personoversikt
