apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: '{{appname}}-demo'
  namespace: tsm
  labels:
    team: tsm
    branchState: '{{branchState}}'
spec:
  port: 3000
  ingresses:
    - '{{ingress}}'
  replicas:
    min: 1
    max: 1
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
